name: vest1
description: "A new Path for Impaired Hearing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  rxdart: ^0.28.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  shared_preferences: ^2.3.1
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.3.0
  location: ^7.0.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.2
  flutter_blue_plus: ^1.34.4
  flutter_google_places_hoc081098: ^2.0.0
  google_api_headers: ^4.2.4
  freezed: ^2.5.7
  flutter_typeahead: ^5.2.0
  http: ^1.2.2
  nowplaying: ^3.0.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffe4cb" # Background color
  image: assets/logo.png # Path to your splash image
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sample3s.mp3
    - assets/Logic - Paul Rodriguez.mp3
    - assets/Logic - Sayonara.mp3
    - .env
    - assets/logo.png


